export interface Content {
  id: string,
  title? : string,
  name? : string,
  release_date?: string,
  first_air_date? : string,
  provider: any,
  genres: Array<{name: string}> | [],
  backdrop_path: string,
  poster_path: string,
  production_countries: Array<any>,
  vote_average: number,
  tagline: string,
  overview: string,
  runtime?: number,
  episode_run_time: Array<string>,
}